baseURL = 'http://example.org/'
languageCode = 'pt-br'
title = 'Diego Brocanelli'
theme = "hugo-PaperMod"
enableRobotsTXT = true
enableEmoji = true
defaultContentLanguage = "pt-br"
hasCJKLanguage = false
paginate = 9
rssLimit = 10
searchHidden = true

[author]
  name = "Diego Brocanelli"
  bio = "asdfasdfasdfasdfasdfasdfasdfasdfasd"
  twitter = "diego_b2"

[Menus]
  main = [
    {Name = "Home", Weight = 10, Identifier = "home", URL = "/"},
    {Name = "Pesquisar", Weight = 10, Identifier = "search", URL = "/search/"},
    {Name = "Sobre", Weight = 10, Identifier = "about", URL = "/about/"}
  ]

[Params]
  subtitle = ""
  description = "Diego Brocanelli Full Stack Developer"
  copyright = "Diego Brocanelli - @diego_b2"
  authorbox = true
  post_navigation = true
  post_meta = ["date", "tags"]
  dateformat = "2006-01-02"
  languageCode = "pt-br"
  mainSections = ["post","posts"]
  comments = true
  rss = true
  ShareButtons = ["linkedin", "twitter"]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  socialIcons = [
    {Name = "twitter", title = "batata", url = "https://batata.com"}
  ]

[params.assets]
  disableHLJS = false

[Params.homeInfoParams]
  Title = "Olá! Meu nome é Diego Brocanelli 👋"
  Content = "Sou desenvolvedor de software, pai e apaixonado por tecnologia."

[Params.cover]
  hidden = false
  hiddenInList = false
  hiddenInSingle = false

[outputs]
  home = [ "HTML", "RSS", "JSON" ]

[params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[markup.highlight]
  codeFences = true
  guessSyntax = true
  lineNos = true
  style = "monokai"
